### ISSUE TITLE
Footer Edits

### ISSUE THREAD

**Issue by elcollins** [InnovativeReelTechnologies/home#103]
- [ ] Remove "about once a month" text
- [ ] First instance of IRT needs superscript ®
- [ ] Pennsylvania to PA in address
- [ ] The listed patents need to be added to, see Erin or April about this
- [ ] Power Grip should be "Spin Power Grip"
- [ ] Change "Pro Staff" to "Pro Staff Application"
- [ ] Change "Media" to "Media Press Kit"
- [ ] Can we left align the Contact section so that the spacing between all of the boxes is even? Then recenter it?
- [ ] Since Privacy Policy/Terms and Conditions are in the footer, do we need it in the main navigation? Remove if we don't.
- [ ] Can we remove the headers that say "Email, Call, Address" and jut have space separating them?

**Comment by ndkline** [comment]
Updated TODO list:

- [ ] ~Remove "about once a month" text~
- [ ] First instance of IRT needs superscript ®
- [ ] Pennsylvania to PA in address
- [ ] The listed patents need to be added to, see Erin or April about this
- [ ] Power Grip should be "Spin Power Grip"
- [ ] Change "Pro Staff" to "Pro Staff Application"
- [ ] Change "Media" to "Media Press Kit"
- [ ] ~Can we left align the Contact section so that the spacing between all of the boxes is even? Then recenter it?~
- [ ] ~Since Privacy Policy/Terms and Conditions are in the footer, do we need it in the main navigation? Remove if we don't.~
- [ ] ~Can we remove the headers that say "Email, Call, Address" and jut have space separating them?~
